# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_new_own.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 0, 291, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAct = QtWidgets.QAction(MainWindow)
        self.openAct.setObjectName("openAct")
        self.printAct = QtWidgets.QAction(MainWindow)
        self.printAct.setEnabled(False)
        self.printAct.setObjectName("printAct")
        self.zoomInAct = QtWidgets.QAction(MainWindow)
        self.zoomInAct.setEnabled(False)
        self.zoomInAct.setObjectName("zoomInAct")
        self.zoomOutAct = QtWidgets.QAction(MainWindow)
        self.zoomOutAct.setObjectName("zoomOutAct")
        self.normalSizeAct = QtWidgets.QAction(MainWindow)
        self.normalSizeAct.setObjectName("normalSizeAct")
        self.fitToWindowAct = QtWidgets.QAction(MainWindow)
        self.fitToWindowAct.setObjectName("fitToWindowAct")
        self.aboutAct = QtWidgets.QAction(MainWindow)
        self.aboutAct.setObjectName("aboutAct")
        self.aboutQtAct = QtWidgets.QAction(MainWindow)
        self.aboutQtAct.setObjectName("aboutQtAct")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Название программы"))
        self.label_2.setText(_translate("MainWindow", "Масштаб карты"))
        self.label.setText(_translate("MainWindow", ":"))
        self.openAct.setText(_translate("MainWindow", "Открыть"))
        self.openAct.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.printAct.setText(_translate("MainWindow", "Печать"))
        self.printAct.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.zoomInAct.setText(_translate("MainWindow", "Увеличить (5%)"))
        self.zoomInAct.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.zoomOutAct.setText(_translate("MainWindow", "Уменьшить (5%)"))
        self.zoomOutAct.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.normalSizeAct.setText(_translate("MainWindow", "Нормальный размер"))
        self.normalSizeAct.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.fitToWindowAct.setText(_translate("MainWindow", "Вместить в окно"))
        self.fitToWindowAct.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.aboutAct.setText(_translate("MainWindow", "О программе"))
        self.aboutQtAct.setText(_translate("MainWindow", " О Qt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
